### ISSUE TITLE
iOS 17.1 crash when using UIDatePicker

### ISSUE THREAD

**Issue by sleivysarnas** [sumup/sumup-ios-sdk#133] opened 2023-10-30 15:59 UTC
We are using 4.3.4 version of SumUp SDK. After we updated to iOS 17.1 our application started crashing when you are trying to select time in UIDatePicker. Removing SumUp SDK fixes the issue. Apparently, it uses method swizzling which does something that crashes the app. Please fix it ASAP because until then our customers will not be able to use SumUp terminals - we are forced to remove it from our application because it crashes in places which are not even related to SumUp. I am attaching stack trace:

`*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'`

<img width="731" alt="image" src="https://github.com/sumup/sumup-ios-sdk/assets/48261482/5a5b521c-3eea-4eb2-895d-51472f9de9b7">

**Comment by mikegunning** [comment] 2023-11-01 12:10
This is happening to us too. Only when selecting a time, picking a date seems fine. Only on iPadOS 17.1.

Can this be addressed soon please.

**Comment by Akhila-ramesh** [comment] 2023-11-02 08:14
This is happening on our app on all devices. Can you please fix this issue as soon as possible.

**Comment by annaafanasyeva-sumup** [comment] 2023-11-02 11:41
Hi @sleivysarnas, so far we have been unable to reproduce the issue.

Could you please verify if it is reproducible in the `SumUpSDKSampleApp` that comes together with the `SumUpSDK` and share the modified `SumUpSDKSampleApp` with us?

**Comment by mikegunning** [comment] 2023-11-02 11:57
I have created a skeleton project that pulls in your cocoapod that causes the date picker to crash. It will only crash on a physical device running iOS17.1.

If I remove the pod, it does not crash. I have tested with all the pods our app uses, and unfortunately it's this pod that crashes it. A lot of customers are also raising this to our support.

**Comment by sleivysarnas** [comment] 2023-11-03 12:50
Strangely, it does not crash on iOS 17.1 with physical device using SumUp sample app. Something must be different in project setup or something is conflicting with other libraries. Will update as soon as I figure this out. Any insights would be appreciated too.

**Comment by annaafanasyeva-sumup** [comment] 2023-11-03 16:24
Hi, we were able to reproduce the issue and currently working on a fix. We will come back to you with an update next week.

**Comment by alexeytarasoff** [comment] 2023-11-08 07:35
The same issue on all the devices on ios17.1 and  ios17.2
How to solve the problem?

**Comment by keySEE** [comment] 2023-11-08 08:50
Hi @annaafanasyeva-sumup,

Can you please advise when you are expecting a new release with the fix will be available?

**Comment by annaafanasyeva-sumup** [comment] 2023-11-08 09:47
Hi, thank you for your patience! We are currently preparing the new release and will make it available later this week.

**Comment by SimoVanigliapro** [comment] 2023-11-08 19:35
> The same issue on all the devices on ios17.1 and ios17.2 How to solve the problem?

the same issue me, if i remove the sumup library works

**Comment by vx8** [comment] 2023-11-10 11:46
Same happening here.. can we have a URGENT fix?

**Comment by SimoVanigliapro** [comment] 2023-11-10 14:18
any news about the new release?

**Comment by annaafanasyeva-sumup** [comment] 2023-11-10 16:57
Hi, please try version `4.4.0` which includes the fix for this issue! It is available under: https://github.com/sumup/sumup-ios-sdk/releases/tag/v4.4.0

**Comment by SimoVanigliapro** [comment] 2023-11-10 17:16
works thanks ;)

**Comment by mikegunning** [comment] 2023-11-10 17:48
I was hoping the minimum deployment would have stayed the same as this was a critical bug. We have a lot of customers on iOS 12 still.

**Comment by SimoVanigliapro** [comment] 2023-11-13 07:33
i need version with last minimun deployment because many customer use it

**Comment by vx8** [comment] 2023-11-13 08:09
wtf... why would you increase the min deployment target by 2 versions for a hotfix??

We have thousands of customers on iOS13..

**Comment by vx8** [comment] 2023-11-14 09:00
Is there an estimated date for the fix with ios13 support?

**Comment by jadeburton-sumup** [comment] 2023-11-14 13:24
We’re sorry for the inconvenience. We are working on SDK 4.3.5, a hotfix release that will fix this issue without changing the minimum deployment target.

It will take some more time for us to release this version based on an older version, as our internal codebase and tooling no longer support iOS 12 and 13.

We will provide a progress update on this later in the week.

**Comment by jadeburton-sumup** [comment] 2023-11-17 14:08
Update on the 4.3.5 hotfix: we are finalizing testing and will release this early next week if all goes well.  For those with a minimum deployment target of 14 or higher, please consider upgrading to [4.4.0](https://github.com/sumup/sumup-ios-sdk/releases/tag/v4.4.0) to fix this issue.

**Comment by mikegunning** [comment] 2023-11-21 09:17
Is there any updates to when to expect 4.3.5?

**Comment by annaafanasyeva-sumup** [comment] 2023-11-21 10:42
Hi, SDK 4.3.5 with iOS 12 & 13 minimum deployment target support is available under: https://github.com/sumup/sumup-ios-sdk/releases/tag/v4.3.5

**Comment by matteobianchi3** [comment] 2023-11-21 13:49
> Hi, SDK 4.3.5 with iOS 12 & 13 minimum deployment target support is available under: https://github.com/sumup/sumup-ios-sdk/releases/tag/v4.3.5.

@annaafanasyeva-sumup how did you manage to solve the issue? (same happens to us with a legacy project still compiled with Xcode 14 😢)

**Comment by SimoVanigliapro** [comment] 2023-11-21 15:25
thanks, now works

**Comment by jadeburton-sumup** [comment] 2023-11-23 09:04
@matteobianchi3 the problem was 2 category methods (`tintColor`, `colorForStyle:`) defined on `UIColor`; the 4.3.5 hotfix renames these to avoid collisions with same-named method(s) in iOS 17, while the 4.4.0 release completely removes them.

**Comment by SimoVanigliapro** [comment] 2023-11-23 09:10
is it normal that after use sumapp payment and loggin inside the page, after some minute re-ask the login?

**Comment by mikegunning** [comment] 2023-11-24 13:25
this has finally fixed [this](https://github.com/sumup/sumup-ios-sdk/issues/109) issue also

**Closed** 2023-11-28 11:07 UTC
