### ISSUE TITLE
Persisting user login

### ISSUE THREAD

**Issue by EddyVerbruggen** [sumup/sumup-ios-sdk#78] opened 2019-06-13 10:24 UTC
Hi friends,

I was wondering how we could prevent users from having to log in all the time?

The SumUp iOS app in the AppStore can be killed after logging in, and when relaunching the app the user is still logged in.

The demo app in this repo does not have this feature. So I wonder how I can accomplish similar behaviour to the SumUp AppStore app with your iOS SDK.

Thanks for any insights,
Eddy

**Comment by Ceroce** [comment] 2019-06-13 10:32
You'll have to log in using OAuth, I'm afraid.
That's what I do in my own app.
See the [The user is logged out when the app is killed](https://github.com/sumup/sumup-ios-sdk/issues/62) issue.

Good luck!

**Comment by EddyVerbruggen** [comment] 2019-06-13 11:06
@Ceroce Thanks, I managed to miss that issue while scanning the repo.

@mollidor Feel free to close this issue in favour of #62, but I'd still like to know how the AppStore app manages to retain login state. If it's done through the keychain, then please share with us how to do so (we probably need to know the exact keychain keys etc to pull this off).

**Comment by jadeburton-sumup** [comment] 2024-07-08 10:25
Closing as duplicate of https://github.com/sumup/sumup-ios-sdk/issues/62

**Closed by jadeburton-sumup** 2024-07-08 10:25 UTC
