### ISSUE TITLE
-[PECLoginSharedVC setAutomaticallyAdjustsScrollViewInsets_backwardCompatibly:]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by swissdev** [sumup/sumup-ios-sdk#7] opened 2015-12-08 15:36 UTC
Hi,

we are receiving this issue when we want to build the project:
-[PECLoginSharedVC setAutomaticallyAdjustsScrollViewInsets_backwardCompatibly:]: unrecognized selector sent to instance 0x15f623b50
2015-12-08 16:34:32.408 POS[2873:762491] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[PECLoginSharedVC setAutomaticallyAdjustsScrollViewInsets_backwardCompatibly:]: unrecognized selector sent to instance 0x15f623b50'

A bit frustrating.. :(
Our code is almost the same as the example project. But we don't use Storyboards in the project right now..

**Comment by mollidor** [comment] 2015-12-08 15:53
Hi,

unfortunately we are unable to reproduce this. Can you try to add `-all_load` to "Other Linker Flags"/`OTHER_LDFLAGS` or add `-force_load path_to_sumup_sdk/SumupSDK.framework/SumupSDK` ? Which version of Xcode are you using, what's your target SDK and deployment target?

Sorry for the inconvenience,
Lukas

**Comment by swissdev** [comment] 2015-12-08 23:15
Hi Lukas,

Thanks for your fast response. It works with -force_load and path to the SDK. :) We are using Xcode Version 7.1.1 (7B1005), deployment target iOS 8.0.

**Comment by schneider-iosphere** [comment] 2015-12-09 10:24
I'll close this for now, as it seems to be resolved. Feel free to reopen it, if further questions arise.

**Closed by schneider-iosphere** 2015-12-09 10:24 UTC
Labels: question

**Comment by test8git** [comment] 2016-08-01 07:52
It not works with -force_load / -all_loads and path to the SDK. :) We are using Xcode Version 7.3.1 (7D1014), deployment target iOS 8.0. Please help us!

**Comment by mollidor** [comment] 2016-08-01 09:23
Hi @test8git.

Let's discuss in the dedicated issue #14 you opened.
