### ISSUE TITLE
Support of Apple Tap to Pay

### ISSUE THREAD

**Issue by curato2** [sumup/sumup-ios-sdk#145] opened 2024-06-26 16:03 UTC
We would like to accept payments with Apple Tap to Pay - however, the SumUP SDK always searches for a card terminal, which is not required in this case. How can I accept Tap to Pay payments here?

**Comment by Nymu5** [comment] 2024-06-26 17:39
As far as I know the SDK does not support that functionality. Although it would be absolutely awesome. 
So the right question would probably be, if there will be an update anytime soon to enable tap to pay.

**Comment by annaafanasyeva-sumup** [comment] 2024-06-28 10:22
Hi folks, we have released the new [iOS SDK v.6.0.0](https://github.com/sumup/sumup-ios-sdk/releases/tag/v6.0.0) with Tap to Pay on iPhone support! Please refer to the [integration documentation](https://github.com/sumup/sumup-ios-sdk/blob/v6.0.0/README.md#tap-to-pay-on-iphone)!

**Comment by jadeburton-sumup** [comment] 2024-07-08 10:50
Closing as duplicate of https://github.com/sumup/sumup-ios-sdk/issues/132

**Closed by jadeburton-sumup** 2024-07-08 10:50 UTC
