### ISSUE TITLE
Absence of "Cancel payment" button in UI considered harmful

### ISSUE THREAD

**Issue by philatkin** [sumup/sumup-ios-sdk#81] opened 2019-07-23 17:22 UTC
The absence of a 'cancel payment' function in the payment flow UI is a showstopper. This is sufficiently big an issue that it must be considered a bug, not a feature request. I have implemented a 'Donation kiosk' app that will be used by a large number of Church of England churches in Truro Diocese, and other denominations worldwide. Right now my app works with iZettle and SumUp, and all these churches are at the purchasing stage - these customers are yours to lose. I cannot recommend SumUp over iZettle unless this bug is fixed. From a church perspective, the device sits unusable for a huge amount of time every time somone wants to cancel, or change their donation amount. Unusable equals lost donations. Note that iZettle have supported 'cancel' since 2012. Please escalate this issue as high as you can go within management - this cannot be a difficult issue to resolve, the functionality is already supported on a hardware button (which is inaccessible when deployed as a donation kiosk).

**Comment by JullianSU** [comment] 2019-07-25 14:59
Hi Philatkin, 

Thank you for your feedback, we understand your point of view but that the way our system is functioning, if we consider changing this we will let you know. Please feel free to reach out at integration@sumup.com for more information. 

Many thanks,

**Comment by PatrickOBoyle** [comment] 2019-12-17 15:39
Doubling up that this is a severe deficiency and we were assure it was a feature that was supported by SumUp

**Comment by si458** [comment] 2020-02-17 15:20
i will tag onto this too if i may,
im using a cordova plugin that links into the sumup sdk,
and once you run checkoutWithRequest, you get the window looking for the read, then the touch or enter card, etc
BUT the is no way of cancelling out of the process if opened by accident,
you have to let it time out and go to the payment declined/transaction cancelled screen automatically after 60 seconds?

**Comment by Ceroce** [comment] 2020-02-17 15:32
> BUT the is no way of cancelling out of the process if opened by accident,
> you have to let it time out and go to the payment declined/transaction cancelled screen automatically after 60 seconds?
No, the user may still press the on/off button to cancel. It's not very discoverable and may be a problem if you physically blocked the access to this button, though.

**Comment by si458** [comment] 2020-02-17 15:35
> > BUT the is no way of cancelling out of the process if opened by accident,
> > you have to let it time out and go to the payment declined/transaction cancelled screen automatically after 60 seconds?
> 
> No, the user may still press the on/off button to cancel. It's not very discoverable and may be a problem if you physically blocked the access to this button, though.

ah right ok, just tried and yep = power button is cancel

abit stupid really when i was clicking the red X thinking that would cancel the process,
and that only works if the customer has already inserted there card and was as the enter pin stage)

**Comment by pierceglennie** [comment] 2020-06-02 17:29
Any update from SumUp on adding a cancel button? It seems like such an obviously useful feature that would resolve one of the biggest problems with the SDK

**Comment by Alkashi** [comment] 2020-09-03 17:05
PLEASE ADD THIS "CANCEL BY CODE" FEATURE :)  
It reminds me that I ever made this request almost 4 years ago. (screen attached)
Really don't understand why it's still not integrated to the sdk. It a basic feature...

![image](https://user-images.githubusercontent.com/7961917/92145231-31c76b80-ee18-11ea-8d22-9001494a4e1b.png)

**Comment by Frederik-VP** [comment] 2021-01-15 09:47
We really really need this. When is this coming? We are struckling with a lot of support from Customers, that don't know why they cannot process a transaction. 

Would it be possible to reduce the reservation of the payment to below 5 min? Like 1 min? Then it would solve our problem for now. And maybe also many other. Until the API update is ready

**Comment by jadeburton-sumup** [comment] 2024-07-08 10:36
I am closing this ticket as a duplicate of https://github.com/sumup/sumup-ios-sdk/issues/6

I will add an update in that ticket.

**Closed by jadeburton-sumup** 2024-07-08 10:36 UTC
