### ISSUE TITLE
unrecognized selector sent to instance 

### ISSUE THREAD

**Issue by princefr** [sumup/sumup-ios-sdk#50] opened 2017-09-13 10:31 UTC
Hi guys i'm implement sumup with a new framework for building apps called fusetools.
integration gone pretty good until now.

Payment works fine in simulator (open the payment view works fine without any crash) but when i try with real devices it crash just after showing me the payment view  with this error  `-[uAppDelegate window]: unrecognized selector sent to instance 0x149e02d20`

i did:
-Link my app against SumupSDK.framework

Link my app against the following system frameworks:
 Accelerate
 AVFoundation
 MapKit

Added -ObjC to "Other Linker Flags"

Added the bundles below provided in SumupSDK.embeddedframework/Resources to my app target:
SumupSDK.embeddedframework/Resources/SMPSharedResources.bundle
 SumupSDK.embeddedframework/Resources/YTLibResources.bundle

The test integration passed.

this what my code looks like

```
    [Foreign(Language.ObjC)]
    public  PayWithToken(string accessToken, string productAmount, string productTitle, string foreignRef)
    @{



      [SumupSDK loginWithToken:accessToken
                       completion: ^(BOOL success, NSError *error) {
                           if (error) {
                            @{PayWithToken:Of(_this).Reject(string):Call(@"token non obtenu")};                          
                           }else{

                                  [SumupSDK prepareForCheckout];
      SMPCheckoutRequest *request = [SMPCheckoutRequest requestWithTotal:[NSDecimalNumber decimalNumberWithString:productAmount]
                                                                   title:productTitle
                                                            currencyCode:[[SumupSDK currentMerchant] currencyCode]
                                                          paymentOptions:SMPPaymentOptionAny];

              [request setForeignTransactionID:foreignRef];

              [SumupSDK checkoutWithRequest: request
                          fromViewController: [UIApplication sharedApplication].keyWindow.rootViewController
                                    completion: ^(SMPCheckoutResult *result, NSError *error) {
                                              if(error)
                                          @{PayWithToken:Of(_this).Reject(string):Call(@"Vous devez etre connecter")};
                                                else
                                          @{PayWithToken:Of(_this).Resolve(string):Call(@"Le paiement a été effectué")};
                                        
                }];

        // something went wrong checkout was not started
        if (![SumupSDK checkoutInProgress]) {
           @{PayWithToken:Of(_this).Reject(string):Call(@"Une erreur de connard s'est produite")};
        }


          }

         }];
    @}
```

[UIApplication sharedApplication].keyWindow.rootViewController represent the iOS view controller.
can anyone help me  here ?

**Comment by shagedorn** [comment] 2017-09-13 11:46
Is `uAppDelegate` a class that you created, or something that fusetools handles for you? Can you see the implementation, and if so, do you see the `window` property/method?

We have no experience with fusetools, but it seems that methods have visibility attributes, as you marked `PayWithToken(…)` with `public`. Could it be that `window` is private?

**Comment by cbaggers** [comment] 2017-09-14 11:20
Hi Chris over at Fuse here. @shagedorn is correct about the error. uAppDelegate doesnt have a `window`. I really don't think the issue is in sumup at all. Over in the fuse forums we havent yet been able to get @princefr's example to get far enough to reproduce the error so it's been tricky to provide more help. 

@princefr if you can give us more info into what you want to pass and what it needs then we can advise you to the best way to do this from within Fuse. We have focused on getting your test case working so far as usually this allows us to explore a bit more autonomously and often to give some better suggestions. However let's do this back in the Fuse thread so as to not clutter up this issue.

**Comment by shagedorn** [comment] 2017-09-14 12:54
@cbaggers thanks for your input. We'll close this issue. Feel free to re-open should any further investigations indicate that there could be an issue in our SDK.

**Closed by shagedorn** 2017-09-14 12:54 UTC

**Comment by viccotr** [comment] 2018-07-16 11:38
Hi, I have the same problem. 
LoginWithToken works correctly but when I start CheckoutWithRequest after connection to SumUp terminal I got this error.

**Comment by mollidor** [comment] 2018-07-16 17:18
@viccotr see my comment in the issue you opened #61
